name: Release Obsidian plugin
on:
    push:
        tags:
            - "*"
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  fileName="obsidian-timekeep-$tag.zip"

                  zip $fileName dist/main.js dist/manifest.json dist/styles.css

                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    $fileName dist/main.js dist/manifest.json dist/styles.css
